import type { ModuleDef } from '../module-definition.js';

const str = (key: string, label: string, extra?: Record<string, unknown>) => ({ key, type: 'string' as const, label, ...extra });
const txt = (key: string, label: string) => ({ key, type: 'text' as const, label });
const num = (key: string, label: string, extra?: Record<string, unknown>) => ({ key, type: 'number' as const, label, ...extra });
const dt = (key: string, label: string, extra?: Record<string, unknown>) => ({ key, type: 'date' as const, label, ...extra });
const bool = (key: string, label: string) => ({ key, type: 'boolean' as const, label });
const en = (key: string, label: string, values: readonly string[], extra?: Record<string, unknown>) => ({ key, type: 'enum' as const, label, enum: values, ...extra });
const ref = (key: string, label: string, to: string, extra?: Record<string, unknown>) => ({ key, type: 'objectid' as const, label, ref: to, ...extra });

export const PHASE3_MODULES: readonly ModuleDef[] = [
  {
    code: 'accounts',
    title: 'Chart of Accounts',
    titleMr: 'खाती',
    collection: 'accounts',
    searchableFields: ['name', 'code'],
    fields: [
      str('code', 'Account Code', { required: true, unique: true }),
      str('name', 'Account Name', { required: true, index: true }),
      en('type', 'Type', ['asset', 'liability', 'income', 'expense', 'equity'], { required: true, index: true }),
      str('parentCode', 'Parent Account Code'),
      num('openingBalance', 'Opening Balance', { default: 0 }),
    ],
    writeDepartments: ['finance'],
  },
  {
    code: 'vouchers',
    title: 'Vouchers',
    titleMr: 'व्हाउचर',
    collection: 'vouchers',
    dateFieldForLock: 'voucherDate',
    searchableFields: ['voucherNumber', 'narration'],
    fields: [
      str('voucherNumber', 'Voucher Number', { unique: true, index: true }),
      en('voucherType', 'Voucher Type', ['payment', 'receipt', 'journal', 'contra', 'purchase', 'expense'], { required: true, index: true }),
      dt('voucherDate', 'Voucher Date', { required: true }),
      txt('narration', 'Narration'),
      num('amount', 'Amount', { required: true }),
      str('debitAccountCode', 'Debit Account'),
      str('creditAccountCode', 'Credit Account'),
      en('status', 'Status', ['draft', 'submitted', 'verified', 'approved'], { default: 'draft', index: true }),
      str('referenceNumber', 'Reference Number'),
    ],
    writeDepartments: ['finance'],
    workflow: {
      field: 'status',
      states: ['draft', 'submitted', 'verified', 'approved'] as const,
      initial: 'draft',
      transitions: { draft: ['submitted'], submitted: ['verified', 'draft'], verified: ['approved', 'submitted'], approved: [] },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
  },
  {
    code: 'incomes',
    title: 'Income Register',
    titleMr: 'उत्पन्न',
    collection: 'incomes',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      en('source', 'Source', ['resident-contribution', 'government-grant', 'donation', 'csr', 'interest', 'rental', 'miscellaneous'], { required: true, index: true }),
      num('amount', 'Amount', { required: true }),
      str('receivedFrom', 'Received From'),
      str('receiptNumber', 'Receipt Number'),
      txt('notes', 'Notes'),
    ],
    writeDepartments: ['finance'],
  },
  {
    code: 'expenses',
    title: 'Expense Register',
    titleMr: 'खर्च',
    collection: 'expenses',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      en('category', 'Category', ['food', 'medicine', 'salary', 'electricity', 'water', 'maintenance', 'fuel', 'laundry', 'stationery', 'internet', 'telephone', 'vehicle', 'miscellaneous'], { required: true, index: true }),
      num('amount', 'Amount', { required: true }),
      str('paidTo', 'Paid To'),
      str('voucherNumber', 'Voucher Number'),
      txt('notes', 'Notes'),
    ],
    writeDepartments: ['finance'],
  },
  {
    code: 'budgets',
    title: 'Budgets',
    titleMr: 'अर्थसंकल्प',
    collection: 'budgets',
    fields: [
      num('financialYear', 'Financial Year', { required: true, index: true }),
      str('department', 'Department'),
      str('category', 'Category'),
      num('allocated', 'Allocated Amount', { required: true }),
      num('spent', 'Spent Amount', { default: 0 }),
      en('status', 'Status', ['draft', 'submitted', 'approved', 'revised'], { default: 'draft', index: true }),
    ],
    writeDepartments: ['finance'],
    workflow: {
      field: 'status',
      states: ['draft', 'submitted', 'approved', 'revised'] as const,
      initial: 'draft',
      transitions: { draft: ['submitted'], submitted: ['approved', 'draft'], approved: ['revised'], revised: ['submitted'] },
      transitionRoles: ['institution-head'],
    },
  },
  {
    code: 'donations',
    title: 'Donations',
    titleMr: 'देणगी',
    collection: 'donations',
    dateFieldForLock: 'donationDate',
    searchableFields: ['donorName', 'receiptNumber'],
    fields: [
      str('donorName', 'Donor Name', { required: true, index: true }),
      str('donorPhone', 'Donor Phone'),
      str('donorEmail', 'Donor Email'),
      str('donorPan', 'Donor PAN'),
      dt('donationDate', 'Donation Date', { required: true }),
      num('amount', 'Amount'),
      en('mode', 'Mode', ['cash', 'cheque', 'upi', 'online', 'bank-transfer', 'in-kind'], { default: 'cash' }),
      en('donationType', 'Donation Type', ['general', 'csr', 'food', 'medicine', 'resident-sponsorship', 'meal-sponsorship', 'recurring', 'anonymous'], { default: 'general', index: true }),
      str('inKindDescription', 'In-kind Description'),
      str('receiptNumber', 'Receipt Number', { unique: true }),
      bool('receipt80GIssued', '80G Receipt Issued'),
      bool('thankYouSent', 'Thank You Sent'),
    ],
    writeDepartments: ['finance', 'reception'],
  },
  {
    code: 'csr-projects',
    title: 'CSR Projects',
    titleMr: 'सीएसआर प्रकल्प',
    collection: 'csr_projects',
    fields: [
      str('company', 'Company Name', { required: true, index: true }),
      str('projectName', 'Project Name', { required: true }),
      str('agreementUrl', 'Agreement Document URL'),
      num('funding', 'Funding Amount'),
      num('utilized', 'Utilized Amount', { default: 0 }),
      dt('startDate', 'Start Date'),
      dt('endDate', 'End Date'),
      en('status', 'Status', ['proposed', 'active', 'completed', 'closed'], { default: 'proposed', index: true }),
      txt('complianceNotes', 'Compliance Notes'),
    ],
    writeDepartments: ['finance'],
  },
  {
    code: 'assets',
    title: 'Asset Register',
    titleMr: 'मालमत्ता',
    collection: 'assets',
    searchableFields: ['assetCode', 'name'],
    fields: [
      str('assetCode', 'Asset ID', { required: true, unique: true }),
      str('name', 'Asset Name', { required: true, index: true }),
      en('category', 'Category', ['furniture', 'bed', 'tv', 'wheelchair', 'medical-equipment', 'vehicle', 'generator', 'computer', 'printer', 'ac', 'solar', 'water-filter', 'other'], { required: true, index: true }),
      str('qrCode', 'QR Code Data'),
      dt('purchaseDate', 'Purchase Date'),
      num('cost', 'Cost'),
      str('supplier', 'Supplier'),
      dt('warrantyExpiry', 'Warranty Expiry'),
      str('amcDetails', 'AMC Details'),
      num('depreciationRate', 'Depreciation % / year'),
      en('status', 'Status', ['in-use', 'in-store', 'under-repair', 'disposed'], { default: 'in-use', index: true }),
      str('location', 'Location'),
    ],
    writeDepartments: ['store'],
  },
  {
    code: 'dead-stock',
    title: 'Dead Stock Register',
    titleMr: 'मृत साठा',
    collection: 'dead_stock',
    fields: [
      ref('assetId', 'Asset', 'assets', { index: true }),
      dt('disposalDate', 'Disposal Date', { required: true }),
      en('disposalType', 'Disposal Type', ['scrap', 'auction', 'write-off'], { required: true }),
      num('realizedAmount', 'Realized Amount'),
      bool('governmentApproval', 'Government Approval Obtained'),
      str('approvalReference', 'Approval Reference'),
      txt('notes', 'Notes'),
    ],
    writeDepartments: ['store', 'finance'],
  },
  {
    code: 'procurements',
    title: 'Procurement',
    titleMr: 'खरेदी',
    collection: 'procurements',
    fields: [
      str('requestNumber', 'Purchase Request Number', { unique: true }),
      dt('requestDate', 'Request Date', { required: true }),
      str('item', 'Item / Service', { required: true }),
      num('quantity', 'Quantity'),
      str('quotationUrls', 'Quotation URLs'),
      str('purchaseOrderNumber', 'PO Number'),
      dt('goodsReceiptDate', 'Goods Receipt Date'),
      str('invoiceNumber', 'Invoice Number'),
      num('invoiceAmount', 'Invoice Amount'),
      ref('vendorId', 'Vendor', 'vendors'),
      en('status', 'Status', ['requested', 'approved', 'ordered', 'received', 'invoiced', 'paid'], { default: 'requested', index: true }),
    ],
    writeDepartments: ['store', 'finance'],
    workflow: {
      field: 'status',
      states: ['requested', 'approved', 'ordered', 'received', 'invoiced', 'paid'] as const,
      initial: 'requested',
      transitions: { requested: ['approved'], approved: ['ordered'], ordered: ['received'], received: ['invoiced'], invoiced: ['paid'], paid: [] },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
  },
  {
    code: 'vendors',
    title: 'Vendors',
    titleMr: 'पुरवठादार',
    collection: 'vendors',
    searchableFields: ['name', 'gst'],
    fields: [
      str('name', 'Vendor Name', { required: true, index: true }),
      str('gst', 'GST Number'),
      str('pan', 'PAN'),
      str('phone', 'Phone'),
      str('email', 'Email'),
      txt('address', 'Address'),
      str('bankDetails', 'Bank Details'),
      str('products', 'Products / Services'),
      num('rating', 'Performance Rating'),
    ],
    writeDepartments: ['store', 'finance'],
  },
  {
    code: 'inventory-items',
    title: 'Inventory Items',
    titleMr: 'साठा वस्तू',
    collection: 'inventory_items',
    searchableFields: ['name'],
    fields: [
      str('name', 'Item Name', { required: true, index: true }),
      en('category', 'Category', ['food', 'medicine', 'cleaning', 'office', 'furniture', 'electrical', 'maintenance'], { required: true, index: true }),
      str('unit', 'Unit'),
      num('currentStock', 'Current Stock', { default: 0 }),
      num('reorderLevel', 'Reorder Level', { default: 5 }),
      dt('expiryDate', 'Expiry Date'),
      str('batchNumber', 'Batch Number'),
    ],
    writeDepartments: ['store'],
  },
  {
    code: 'inventory-moves',
    title: 'Inventory Movements',
    titleMr: 'साठा हालचाल',
    collection: 'inventory_moves',
    dateFieldForLock: 'date',
    fields: [
      ref('itemId', 'Item', 'inventory_items', { required: true, index: true }),
      dt('date', 'Date', { required: true }),
      en('type', 'Type', ['stock-in', 'stock-out', 'transfer', 'adjustment'], { required: true }),
      num('quantity', 'Quantity', { required: true }),
      str('reason', 'Reason'),
      str('referenceNumber', 'Reference Number'),
    ],
    writeDepartments: ['store'],
  },
  {
    code: 'employees',
    title: 'Employees',
    titleMr: 'कर्मचारी',
    collection: 'employees',
    searchableFields: ['fullName', 'employeeCode'],
    fields: [
      str('employeeCode', 'Employee ID', { required: true, unique: true }),
      str('fullName', 'Full Name', { required: true, index: true }),
      str('photoUrl', 'Photo URL'),
      str('aadhaar', 'Aadhaar'),
      str('pan', 'PAN'),
      str('qualification', 'Qualification'),
      dt('joiningDate', 'Joining Date'),
      str('department', 'Department', { index: true }),
      str('designation', 'Designation'),
      num('salary', 'Monthly Salary'),
      bool('policeVerified', 'Police Verification Done'),
      str('emergencyContact', 'Emergency Contact'),
      str('bankDetails', 'Bank Details'),
      str('documentsUrls', 'Document URLs'),
      en('status', 'Status', ['active', 'on-leave', 'resigned', 'terminated'], { default: 'active', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'payrolls',
    title: 'Payroll',
    titleMr: 'वेतनपत्र',
    collection: 'payrolls',
    dateFieldForLock: 'generatedDate',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      num('year', 'Year', { required: true, index: true }),
      num('month', 'Month', { required: true, index: true }),
      num('basic', 'Basic', { required: true }),
      num('hra', 'HRA'),
      num('allowances', 'Allowances'),
      num('deductions', 'Deductions'),
      num('advance', 'Advance'),
      num('loan', 'Loan Deduction'),
      num('bonus', 'Bonus'),
      num('netPay', 'Net Pay', { required: true }),
      en('status', 'Status', ['draft', 'approved', 'paid'], { default: 'draft', index: true }),
      dt('paidDate', 'Paid Date'),
    ],
    writeDepartments: ['hr', 'finance'],
    workflow: {
      field: 'status',
      states: ['draft', 'approved', 'paid'] as const,
      initial: 'draft',
      transitions: { draft: ['approved'], approved: ['paid'], paid: [] },
      transitionRoles: ['institution-head'],
    },
  },
  {
    code: 'leaves',
    title: 'Leave Management',
    titleMr: 'रजा',
    collection: 'leaves',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      en('leaveType', 'Leave Type', ['casual', 'medical', 'earned', 'maternity'], { required: true }),
      dt('fromDate', 'From Date', { required: true }),
      dt('toDate', 'To Date', { required: true }),
      str('reason', 'Reason'),
      en('status', 'Status', ['applied', 'approved', 'rejected', 'cancelled'], { default: 'applied', index: true }),
      str('approvedBy', 'Approved By'),
    ],
    writeDepartments: ['hr'],
    workflow: {
      field: 'status',
      states: ['applied', 'approved', 'rejected', 'cancelled'] as const,
      initial: 'applied',
      transitions: { applied: ['approved', 'rejected', 'cancelled'], approved: [], rejected: [], cancelled: [] },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
  },
  {
    code: 'trust-meetings',
    title: 'Trust & Committee Meetings',
    titleMr: 'ट्रस्ट बैठका',
    collection: 'trust_meetings',
    fields: [
      dt('meetingDate', 'Meeting Date', { required: true }),
      str('meetingType', 'Meeting Type'),
      txt('agenda', 'Agenda'),
      str('attendees', 'Attendees'),
      txt('discussion', 'Discussion'),
      txt('decisions', 'Decisions'),
      txt('actionItems', 'Action Items'),
      str('minutesDocumentUrl', 'Minutes Document URL'),
      str('digitalSignatureUrl', 'Digital Signature URL'),
    ],
    writeRoles: ['institution-head', 'assistant-manager'],
  },
  {
    code: 'resolutions',
    title: 'Resolution Register',
    titleMr: 'ठराव नोंदवही',
    collection: 'resolutions',
    fields: [
      str('resolutionNumber', 'Resolution Number', { required: true, unique: true }),
      dt('meetingDate', 'Meeting Date'),
      txt('proposal', 'Proposal'),
      str('votingResult', 'Voting Result'),
      en('status', 'Status', ['proposed', 'approved', 'implemented', 'closed'], { default: 'proposed', index: true }),
      dt('implementationDate', 'Implementation Date'),
    ],
    writeRoles: ['institution-head', 'assistant-manager'],
  },
  {
    code: 'complaints',
    title: 'Complaints',
    titleMr: 'तक्रारी',
    collection: 'complaints',
    searchableFields: ['subject'],
    fields: [
      en('complainantType', 'Complainant Type', ['resident', 'family', 'employee', 'citizen', 'anonymous'], { required: true }),
      str('complainantName', 'Complainant Name'),
      dt('complaintDate', 'Complaint Date', { required: true, index: true }),
      str('subject', 'Subject', { required: true }),
      txt('description', 'Description'),
      str('assignedTo', 'Assigned To'),
      en('status', 'Status', ['open', 'investigating', 'resolved', 'closed'], { default: 'open', index: true }),
      txt('resolutionNotes', 'Resolution Notes'),
      str('feedback', 'Feedback'),
    ],
    workflow: {
      field: 'status',
      states: ['open', 'investigating', 'resolved', 'closed'] as const,
      initial: 'open',
      transitions: { open: ['investigating'], investigating: ['resolved'], resolved: ['closed'], closed: [] },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
  },
  {
    code: 'suggestions',
    title: 'Suggestion Register',
    titleMr: 'सूचना नोंदवही',
    collection: 'suggestions',
    fields: [
      dt('date', 'Date', { required: true }),
      str('from', 'From'),
      txt('suggestion', 'Suggestion', ),
      str('department', 'Department'),
      txt('actionTaken', 'Action Taken'),
      en('status', 'Status', ['received', 'reviewed', 'acted', 'closed'], { default: 'received', index: true }),
    ],
  },
  {
    code: 'licenses',
    title: 'Licenses & Compliance',
    titleMr: 'परवाने',
    collection: 'licenses',
    fields: [
      en('licenseType', 'License Type', ['registration', 'fire-noc', 'building', 'food', 'electrical-audit', 'water-test', 'lift', 'insurance', 'other'], { required: true, index: true }),
      str('licenseNumber', 'License Number'),
      dt('issueDate', 'Issue Date'),
      dt('expiryDate', 'Expiry Date', { index: true }),
      str('documentUrl', 'Document URL'),
      en('status', 'Status', ['active', 'expiring-soon', 'expired', 'renewed'], { default: 'active', index: true }),
      txt('notes', 'Notes'),
    ],
    writeRoles: ['institution-head', 'assistant-manager'],
  },
  {
    code: 'grants',
    title: 'Government Grants',
    titleMr: 'शासकीय अनुदान',
    collection: 'grants',
    fields: [
      str('grantName', 'Grant Name', { required: true, index: true }),
      str('scheme', 'Scheme'),
      dt('applicationDate', 'Application Date'),
      num('requestedAmount', 'Requested Amount', { required: true }),
      num('approvedAmount', 'Approved Amount'),
      num('releasedAmount', 'Released Amount'),
      num('utilizedAmount', 'Utilized Amount', { default: 0 }),
      dt('releaseDate', 'Release Date'),
      str('ucDocumentUrl', 'Utilization Certificate URL'),
      en('status', 'Status', ['applied', 'verified', 'approved', 'released', 'utilized', 'closed', 'rejected'], { default: 'applied', index: true }),
    ],
    writeDepartments: ['finance'],
    workflow: {
      field: 'status',
      states: ['applied', 'verified', 'approved', 'released', 'utilized', 'closed', 'rejected'] as const,
      initial: 'applied',
      transitions: { applied: ['verified', 'rejected'], verified: ['approved', 'rejected'], approved: ['released'], released: ['utilized'], utilized: ['closed'], closed: [], rejected: [] },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
  },
  {
    code: 'audits',
    title: 'Audit Management',
    titleMr: 'लेखापरीक्षण',
    collection: 'audits',
    fields: [
      en('auditType', 'Audit Type', ['internal', 'external', 'government', 'financial', 'compliance', 'medical', 'food', 'safety', 'hr'], { required: true, index: true }),
      dt('auditDate', 'Audit Date', { required: true }),
      str('auditorName', 'Auditor Name'),
      txt('findings', 'Findings'),
      txt('correctiveActions', 'Corrective Actions'),
      num('score', 'Audit Score'),
      en('status', 'Status', ['scheduled', 'in-progress', 'completed', 'closed'], { default: 'scheduled', index: true }),
      str('reportUrl', 'Audit Report URL'),
    ],
  },
  {
    code: 'bank-transactions',
    title: 'Bank Book',
    titleMr: 'बँक पुस्तक',
    collection: 'bank_transactions',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      en('type', 'Type', ['deposit', 'withdrawal', 'transfer', 'upi', 'neft', 'rtgs', 'cheque'], { required: true }),
      num('amount', 'Amount', { required: true }),
      str('bankName', 'Bank Name'),
      str('accountNumber', 'Account Number'),
      str('referenceNumber', 'Reference / Cheque Number'),
      bool('reconciled', 'Reconciled'),
      txt('notes', 'Notes'),
    ],
    writeDepartments: ['finance'],
  },
  {
    code: 'cash-book',
    title: 'Cash Book',
    titleMr: 'रोकड पुस्तक',
    collection: 'cash_book',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      en('type', 'Type', ['receipt', 'payment', 'opening', 'closing', 'verification', 'adjustment'], { required: true }),
      num('amount', 'Amount', { required: true }),
      str('particulars', 'Particulars'),
      num('runningBalance', 'Running Balance'),
      str('verifiedBy', 'Verified By'),
    ],
    writeDepartments: ['finance'],
  },
  {
    code: 'recruitments',
    title: 'Recruitments',
    titleMr: 'भरती',
    collection: 'recruitments',
    searchableFields: ['position'],
    fields: [
      str('position', 'Position', { required: true, index: true }),
      str('department', 'Department'),
      num('vacancies', 'Vacancies', { default: 1 }),
      en('status', 'Status', ['open', 'on-hold', 'closed', 'cancelled'], { default: 'open', index: true }),
      dt('appliedDate', 'Applied Date'),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'confirmations',
    title: 'Probation Confirmations',
    titleMr: 'पुष्टीकरण',
    collection: 'confirmations',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      dt('confirmationDate', 'Confirmation Date', { required: true }),
      dt('probationEndDate', 'Probation End Date', { required: true }),
      en('status', 'Status', ['pending', 'confirmed', 'rejected'], { default: 'pending', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'promotions',
    title: 'Promotions',
    titleMr: 'पदोन्नती',
    collection: 'promotions',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      str('fromDesignation', 'From Designation', { required: true }),
      str('toDesignation', 'To Designation', { required: true }),
      dt('promotionDate', 'Promotion Date', { required: true }),
      en('status', 'Status', ['proposed', 'approved', 'effective', 'cancelled'], { default: 'proposed', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'employee-transfers',
    title: 'Employee Transfers',
    titleMr: 'बदली',
    collection: 'employee_transfers',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      str('fromDepartment', 'From Department', { required: true }),
      str('toDepartment', 'To Department', { required: true }),
      dt('transferDate', 'Transfer Date', { required: true }),
      txt('reason', 'Reason'),
      en('status', 'Status', ['proposed', 'approved', 'effective', 'cancelled'], { default: 'proposed', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'resignations',
    title: 'Resignations',
    titleMr: 'राजीनामे',
    collection: 'resignations',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      dt('resignationDate', 'Resignation Date', { required: true }),
      dt('lastWorkingDay', 'Last Working Day'),
      txt('reason', 'Reason'),
      en('status', 'Status', ['submitted', 'accepted', 'withdrawn'], { default: 'submitted', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'terminations',
    title: 'Terminations',
    titleMr: 'सेवासमाप्ती',
    collection: 'terminations',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      dt('terminationDate', 'Termination Date', { required: true }),
      txt('reason', 'Reason'),
      bool('noticePeriodServed', 'Notice Period Served'),
      en('status', 'Status', ['initiated', 'approved', 'completed'], { default: 'initiated', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'performance-reviews',
    title: 'Performance Reviews',
    titleMr: 'कामगिरी मूल्यांकन',
    collection: 'performance_reviews',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      str('reviewPeriod', 'Review Period', { required: true }),
      num('rating', 'Rating'),
      txt('goals', 'Goals'),
      str('reviewer', 'Reviewer'),
      en('status', 'Status', ['draft', 'submitted', 'reviewed', 'closed'], { default: 'draft', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'trainings',
    title: 'Trainings',
    titleMr: 'प्रशिक्षण',
    collection: 'trainings',
    searchableFields: ['title'],
    fields: [
      str('title', 'Title', { required: true, index: true }),
      str('department', 'Department'),
      str('trainer', 'Trainer'),
      dt('date', 'Date', { required: true }),
      txt('attendees', 'Attendees'),
      en('status', 'Status', ['planned', 'completed', 'cancelled'], { default: 'planned', index: true }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'certificates',
    title: 'Employee Certificates',
    titleMr: 'प्रमाणपत्रे',
    collection: 'certificates',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      str('certificateName', 'Certificate Name', { required: true, index: true }),
      str('issuedBy', 'Issued By'),
      dt('issueDate', 'Issue Date'),
      dt('expiryDate', 'Expiry Date', { index: true }),
      str('documentUrl', 'Document URL'),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'trust-profiles',
    title: 'Trust Profiles',
    titleMr: 'ट्रस्ट माहिती',
    collection: 'trust_profiles',
    searchableFields: ['trustName', 'registrationNumber'],
    fields: [
      str('trustName', 'Trust Name', { required: true, index: true }),
      str('registrationNumber', 'Registration Number', { unique: true }),
      dt('registeredDate', 'Registered Date'),
      txt('address', 'Address'),
      txt('objectives', 'Objectives'),
      str('documentUrl', 'Document URL'),
    ],
    writeRoles: ['institution-head', 'assistant-manager'],
  },
  {
    code: 'trustees',
    title: 'Trustees',
    titleMr: 'ट्रस्टी',
    collection: 'trustees',
    searchableFields: ['name'],
    fields: [
      ref('trustProfileId', 'Trust Profile', 'trust_profiles', { required: true, index: true }),
      str('name', 'Name', { required: true, index: true }),
      str('designation', 'Designation'),
      str('phone', 'Phone'),
      str('email', 'Email'),
      dt('tenureStart', 'Tenure Start'),
      dt('tenureEnd', 'Tenure End'),
      en('status', 'Status', ['active', 'inactive'], { default: 'active', index: true }),
    ],
    writeRoles: ['institution-head', 'assistant-manager'],
  },
];
