import type { ModuleDef } from '../module-definition.js';

const str = (key: string, label: string, extra?: Record<string, unknown>) => ({ key, type: 'string' as const, label, ...extra });
const txt = (key: string, label: string) => ({ key, type: 'text' as const, label });
const num = (key: string, label: string, extra?: Record<string, unknown>) => ({ key, type: 'number' as const, label, ...extra });
const dt = (key: string, label: string, extra?: Record<string, unknown>) => ({ key, type: 'date' as const, label, ...extra });
const bool = (key: string, label: string) => ({ key, type: 'boolean' as const, label });
const en = (key: string, label: string, values: readonly string[], extra?: Record<string, unknown>) => ({ key, type: 'enum' as const, label, enum: values, ...extra });
const ref = (key: string, label: string, to: string, extra?: Record<string, unknown>) => ({ key, type: 'objectid' as const, label, ref: to, ...extra });

export const PHASE2_MODULES: readonly ModuleDef[] = [
  {
    code: 'residents',
    title: 'Residents',
    titleMr: 'रहिवासी',
    collection: 'residents',
    dateFieldForLock: 'admissionDate',
    searchableFields: ['fullName', 'residentNumber', 'aadhaar'],
    fields: [
      str('residentNumber', 'Resident Number', { unique: true, index: true }),
      str('fullName', 'Full Name', { required: true, index: true }),
      str('fullNameMr', 'Full Name (Marathi)'),
      str('photoUrl', 'Photo URL'),
      str('qrCode', 'QR Code Data'),
      dt('admissionDate', 'Admission Date'),
      en('status', 'Status', ['active', 'discharged', 'transferred', 'deceased', 'absconded'], { default: 'active', index: true }),
      str('aadhaar', 'Aadhaar', { index: true }),
      str('pan', 'PAN'),
      str('abhaId', 'ABHA ID'),
      str('bloodGroup', 'Blood Group'),
      en('gender', 'Gender', ['male', 'female', 'other'], { required: true }),
      dt('dob', 'Date of Birth'),
      num('age', 'Age'),
      str('religion', 'Religion'),
      str('category', 'Category'),
      txt('address', 'Address'),
      str('guardianName', 'Guardian Name'),
      str('guardianPhone', 'Guardian Phone'),
      str('nomineeName', 'Nominee Name'),
      str('emergencyContactName', 'Emergency Contact Name'),
      str('emergencyContactPhone', 'Emergency Contact Phone'),
      str('occupation', 'Occupation'),
      num('income', 'Monthly Income'),
      str('pensionDetails', 'Pension Details'),
      str('insuranceDetails', 'Insurance Details'),
      str('disability', 'Disability'),
      txt('personalBelongings', 'Personal Belongings'),
      ref('roomId', 'Room', 'rooms'),
      ref('bedId', 'Bed', 'beds'),
      str('digitalSignatureUrl', 'Digital Signature URL'),
    ],
  },
  {
    code: 'family-members',
    title: 'Family Members',
    titleMr: 'कुटुंब',
    collection: 'family_members',
    searchableFields: ['name'],
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      str('name', 'Name', { required: true }),
      en('relation', 'Relation', ['parent', 'child', 'spouse', 'sibling', 'guardian', 'legal-guardian', 'emergency-contact', 'other'], { required: true }),
      str('phone', 'Phone'),
      str('email', 'Email'),
      txt('address', 'Address'),
      bool('visitPermission', 'Visit Permission'),
      bool('videoCallPermission', 'Video Call Permission'),
      bool('notificationOptIn', 'Notification Opt-in'),
    ],
  },
  {
    code: 'rooms',
    title: 'Rooms',
    titleMr: 'खोल्या',
    collection: 'rooms',
    searchableFields: ['roomNumber', 'building'],
    fields: [
      str('building', 'Building', { required: true, index: true }),
      str('floor', 'Floor'),
      str('roomNumber', 'Room Number', { required: true }),
      en('roomType', 'Room Type', ['single', 'double', 'shared', 'isolation', 'icu', 'general'], { default: 'shared' }),
      num('capacity', 'Capacity', { default: 1 }),
      en('status', 'Status', ['active', 'maintenance', 'closed'], { default: 'active' }),
      en('cleaningStatus', 'Cleaning Status', ['clean', 'dirty', 'in-progress'], { default: 'clean' }),
      en('genderRestriction', 'Gender Restriction', ['none', 'male', 'female'], { default: 'none' }),
      bool('medicalIsolation', 'Medical Isolation'),
    ],
  },
  {
    code: 'beds',
    title: 'Beds',
    titleMr: 'पलंग',
    collection: 'beds',
    searchableFields: ['bedCode'],
    fields: [
      ref('roomId', 'Room', 'rooms', { required: true, index: true }),
      str('bedCode', 'Bed Code', { required: true, unique: true }),
      str('qrCode', 'QR Code Data'),
      en('status', 'Status', ['vacant', 'occupied', 'reserved', 'maintenance'], { default: 'vacant', index: true }),
      ref('currentResidentId', 'Current Resident', 'residents'),
    ],
  },
  {
    code: 'medical-records',
    title: 'Medical Records (EHR)',
    titleMr: 'वैद्यकीय नोंदी',
    collection: 'medical_records',
    dateFieldForLock: 'recordDate',
    searchableFields: ['diagnosis'],
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('recordDate', 'Record Date', { required: true }),
      str('diagnosis', 'Diagnosis'),
      txt('doctorNotes', 'Doctor Notes'),
      num('temperature', 'Temperature (°F)'),
      num('pulse', 'Pulse'),
      str('bloodPressure', 'Blood Pressure'),
      num('sugar', 'Sugar (mg/dL)'),
      num('weight', 'Weight (kg)'),
      num('height', 'Height (cm)'),
      num('bmi', 'BMI'),
      txt('prescription', 'Prescription'),
      str('hospitalReferral', 'Hospital Referral'),
      str('labReportUrls', 'Lab Report URLs'),
    ],
  },
  {
    code: 'nurse-rounds',
    title: 'Nurse Rounds',
    titleMr: 'परिचारिका फेरी',
    collection: 'nurse_rounds',
    dateFieldForLock: 'roundDate',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('roundDate', 'Round Date', { required: true }),
      en('shift', 'Shift', ['morning', 'afternoon', 'night'], { required: true }),
      str('vitalsSummary', 'Vitals Summary'),
      txt('medicineAdministered', 'Medicine Administered'),
      txt('observationNotes', 'Observation Notes'),
      txt('emergencyNotes', 'Emergency Notes'),
      txt('doctorFollowUp', 'Doctor Follow-up'),
      txt('shiftHandover', 'Shift Handover'),
    ],
    writeDepartments: ['nurse'],
  },
  {
    code: 'doctor-visits',
    title: 'Doctor Visits',
    titleMr: 'डॉक्टर भेटी',
    collection: 'doctor_visits',
    dateFieldForLock: 'visitDate',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('visitDate', 'Visit Date', { required: true }),
      str('doctorName', 'Doctor Name', { required: true }),
      str('diagnosis', 'Diagnosis'),
      txt('prescription', 'Prescription'),
      txt('medicalAdvice', 'Medical Advice'),
      str('referral', 'Referral'),
      str('certificateUrl', 'Medical Certificate URL'),
    ],
    writeDepartments: ['doctor'],
  },
  {
    code: 'medicines',
    title: 'Medicines',
    titleMr: 'औषधे',
    collection: 'medicines',
    searchableFields: ['name', 'category'],
    fields: [
      str('name', 'Medicine Name', { required: true, index: true }),
      str('category', 'Category'),
      str('unit', 'Unit'),
      num('reorderLevel', 'Reorder Level', { default: 10 }),
    ],
    writeDepartments: ['doctor', 'store'],
  },
  {
    code: 'pharmacy-stock',
    title: 'Pharmacy Stock',
    titleMr: 'औषध साठा',
    collection: 'pharmacy_stock',
    dateFieldForLock: 'receivedDate',
    searchableFields: ['batchNumber', 'supplier'],
    fields: [
      ref('medicineId', 'Medicine', 'medicines', { required: true, index: true }),
      str('batchNumber', 'Batch Number'),
      num('quantity', 'Quantity', { required: true }),
      dt('expiryDate', 'Expiry Date', { index: true }),
      dt('receivedDate', 'Received Date'),
      str('supplier', 'Supplier'),
      num('unitPrice', 'Unit Price'),
    ],
    writeDepartments: ['store', 'doctor'],
  },
  {
    code: 'medicine-issues',
    title: 'Medicine Issues',
    titleMr: 'औषध वितरण',
    collection: 'medicine_issues',
    dateFieldForLock: 'issueDate',
    fields: [
      ref('medicineId', 'Medicine', 'medicines', { required: true, index: true }),
      ref('residentId', 'Resident', 'residents', { index: true }),
      dt('issueDate', 'Issue Date', { required: true }),
      num('quantity', 'Quantity', { required: true }),
      en('type', 'Type', ['issue', 'return'], { default: 'issue' }),
      str('issuedBy', 'Issued By'),
    ],
    writeDepartments: ['nurse', 'store'],
  },
  {
    code: 'resident-attendance',
    title: 'Resident Attendance',
    titleMr: 'रहिवासी उपस्थिती',
    collection: 'resident_attendance',
    dateFieldForLock: 'date',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('date', 'Date', { required: true, index: true }),
      en('status', 'Status', ['present', 'absent', 'leave', 'hospital'], { default: 'present' }),
      str('absenceReason', 'Absence Reason'),
      en('captureMethod', 'Capture Method', ['manual', 'qr', 'biometric', 'face'], { default: 'manual' }),
      bool('nightAttendance', 'Night Attendance'),
    ],
    writeDepartments: ['nurse', 'reception'],
  },
  {
    code: 'employee-attendance',
    title: 'Employee Attendance',
    titleMr: 'कर्मचारी उपस्थिती',
    collection: 'employee_attendance',
    dateFieldForLock: 'date',
    fields: [
      ref('employeeId', 'Employee', 'employees', { required: true, index: true }),
      dt('date', 'Date', { required: true, index: true }),
      en('status', 'Status', ['present', 'absent', 'half-day', 'leave'], { default: 'present' }),
      str('checkIn', 'Check-in Time'),
      str('checkOut', 'Check-out Time'),
      en('captureMethod', 'Capture Method', ['manual', 'qr', 'biometric', 'face'], { default: 'manual' }),
    ],
    writeDepartments: ['hr'],
  },
  {
    code: 'visitors',
    title: 'Visitors',
    titleMr: 'भेटीची नोंद',
    collection: 'visitors',
    dateFieldForLock: 'entryTime',
    searchableFields: ['visitorName', 'phone'],
    fields: [
      str('visitorName', 'Visitor Name', { required: true }),
      str('phone', 'Phone'),
      str('photoUrl', 'Photo URL'),
      str('idProof', 'ID Proof'),
      str('purpose', 'Purpose'),
      dt('entryTime', 'Entry Time', { required: true }),
      dt('exitTime', 'Exit Time'),
      ref('residentId', 'Resident', 'residents', { index: true }),
      en('status', 'Status', ['checked-in', 'checked-out', 'blacklisted'], { default: 'checked-in' }),
      str('passCode', 'Visitor Pass Code'),
    ],
    writeDepartments: ['reception', 'security'],
  },
  {
    code: 'kitchen-menus',
    title: 'Kitchen Menus',
    titleMr: 'स्वयंपाक मेनू',
    collection: 'kitchen_menus',
    dateFieldForLock: 'menuDate',
    fields: [
      dt('menuDate', 'Menu Date', { required: true, index: true }),
      str('breakfast', 'Breakfast'),
      str('lunch', 'Lunch'),
      str('dinner', 'Dinner'),
      str('specialDiet', 'Special Diet'),
      txt('nutritionNotes', 'Nutrition Notes'),
    ],
    writeDepartments: ['kitchen'],
  },
  {
    code: 'meal-attendance',
    title: 'Meal Attendance',
    titleMr: 'जेवण उपस्थिती',
    collection: 'meal_attendance',
    dateFieldForLock: 'date',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('date', 'Date', { required: true, index: true }),
      en('meal', 'Meal', ['breakfast', 'lunch', 'dinner'], { required: true }),
      en('status', 'Status', ['taken', 'skipped', 'special'], { default: 'taken' }),
      str('consumptionNotes', 'Consumption Notes'),
    ],
    writeDepartments: ['kitchen', 'nurse'],
  },
  {
    code: 'diet-plans',
    title: 'Diet Plans',
    titleMr: 'आहार योजना',
    collection: 'diet_plans',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      en('dietType', 'Diet Type', ['diabetic', 'low-salt', 'liquid', 'high-protein', 'custom'], { required: true }),
      txt('doctorRecommendation', 'Doctor Recommendation'),
      txt('customPlan', 'Custom Plan'),
      dt('startDate', 'Start Date'),
      dt('endDate', 'End Date'),
      en('status', 'Status', ['active', 'completed', 'cancelled'], { default: 'active' }),
    ],
    writeDepartments: ['doctor', 'kitchen'],
  },
  {
    code: 'store-consumption',
    title: 'Store Consumption',
    titleMr: 'साठा वापर',
    collection: 'store_consumption',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      en('item', 'Item', ['rice', 'wheat', 'milk', 'vegetables', 'fruits', 'oil', 'gas', 'medicine', 'other'], { required: true }),
      str('itemOther', 'Other Item'),
      num('quantity', 'Quantity', { required: true }),
      str('unit', 'Unit'),
      en('period', 'Period', ['daily', 'monthly'], { default: 'daily' }),
      str('notes', 'Notes'),
    ],
    writeDepartments: ['store', 'kitchen'],
  },
  {
    code: 'laundry',
    title: 'Laundry',
    titleMr: 'धुलाई',
    collection: 'laundry',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      ref('residentId', 'Resident', 'residents', { index: true }),
      en('type', 'Type', ['issue', 'receive'], { required: true }),
      str('items', 'Items'),
      num('count', 'Item Count'),
      en('status', 'Status', ['normal', 'lost', 'damaged'], { default: 'normal' }),
      str('notes', 'Notes'),
    ],
    writeDepartments: ['laundry'],
  },
  {
    code: 'housekeeping',
    title: 'Housekeeping',
    titleMr: 'घरकाम',
    collection: 'housekeeping',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      en('task', 'Task', ['room-cleaning', 'bathroom-cleaning', 'sanitization', 'waste-collection', 'pest-control', 'other'], { required: true }),
      str('area', 'Area / Room'),
      str('assignedTo', 'Assigned To'),
      en('status', 'Status', ['pending', 'in-progress', 'completed', 'verified'], { default: 'pending' }),
      txt('checklist', 'Checklist'),
    ],
    writeDepartments: ['housekeeping', 'maintenance'],
  },
  {
    code: 'maintenance-requests',
    title: 'Maintenance Requests',
    titleMr: 'देखभाल विनंत्या',
    collection: 'maintenance_requests',
    fields: [
      dt('complaintDate', 'Complaint Date', { required: true }),
      str('area', 'Area / Room'),
      txt('description', 'Description', ),
      str('workOrderNumber', 'Work Order Number'),
      str('assignedStaff', 'Assigned Staff'),
      en('status', 'Status', ['open', 'assigned', 'in-progress', 'completed', 'verified'], { default: 'open', index: true }),
      dt('completedDate', 'Completion Date'),
      num('cost', 'Cost'),
    ],
    writeDepartments: ['maintenance'],
    workflow: {
      field: 'status',
      states: ['open', 'assigned', 'in-progress', 'completed', 'verified'] as const,
      initial: 'open',
      transitions: { open: ['assigned'], assigned: ['in-progress'], 'in-progress': ['completed'], completed: ['verified'] },
    },
  },
  {
    code: 'emergencies',
    title: 'Emergencies',
    titleMr: 'आपत्काल',
    collection: 'emergencies',
    dateFieldForLock: 'alertTime',
    fields: [
      dt('alertTime', 'Alert Time', { required: true }),
      ref('residentId', 'Resident', 'residents', { index: true }),
      en('type', 'Type', ['medical', 'fire', 'missing', 'disaster', 'outbreak', 'other'], { required: true }),
      txt('description', 'Description'),
      bool('doctorNotified', 'Doctor Notified'),
      bool('ambulanceCalled', 'Ambulance Called'),
      str('hospital', 'Hospital'),
      bool('familyNotified', 'Family Notified'),
      en('status', 'Status', ['active', 'resolved'], { default: 'active', index: true }),
      txt('incidentLog', 'Incident Log'),
    ],
  },
  {
    code: 'incidents',
    title: 'Incident Register',
    titleMr: 'घटना नोंदवही',
    collection: 'incidents',
    dateFieldForLock: 'incidentDate',
    fields: [
      dt('incidentDate', 'Incident Date', { required: true }),
      ref('residentId', 'Resident', 'residents', { index: true }),
      en('type', 'Type', ['fall', 'injury', 'medical-emergency', 'behavioral', 'property-damage', 'fire', 'security'], { required: true }),
      txt('description', 'Description'),
      str('actionTaken', 'Action Taken'),
      str('reportedTo', 'Reported To'),
      en('severity', 'Severity', ['low', 'medium', 'high', 'critical'], { default: 'low' }),
    ],
  },
  {
    code: 'daily-register',
    title: 'Daily Register',
    titleMr: 'दैनिक नोंदवही',
    collection: 'daily_register',
    dateFieldForLock: 'date',
    fields: [
      dt('date', 'Date', { required: true, index: true }),
      str('department', 'Department'),
      txt('summary', 'Day Summary'),
      num('presentResidents', 'Present Residents'),
      num('presentStaff', 'Present Staff'),
      txt('remarks', 'Remarks'),
      en('status', 'Status', ['draft', 'submitted', 'verified', 'approved', 'locked'], { default: 'draft', index: true }),
    ],
    workflow: {
      field: 'status',
      states: ['draft', 'submitted', 'verified', 'approved', 'locked'] as const,
      initial: 'draft',
      transitions: {
        draft: ['submitted'],
        submitted: ['verified', 'draft'],
        verified: ['approved', 'submitted'],
        approved: ['locked'],
        locked: [],
      },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
  },
  {
    code: 'deaths',
    title: 'Death Register',
    titleMr: 'मृत्यू नोंदवही',
    collection: 'deaths',
    dateFieldForLock: 'deathDate',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('deathDate', 'Date of Death', { required: true }),
      str('deathTime', 'Time of Death'),
      str('cause', 'Cause of Death'),
      str('doctorCertificateUrl', 'Doctor Certificate URL'),
      bool('governmentReported', 'Reported to Government'),
      bool('familyNotified', 'Family Notified'),
      str('deathCertificateUrl', 'Death Certificate URL'),
      bool('residentArchived', 'Resident Archived'),
    ],
    writeDepartments: ['doctor'],
  },
  {
    code: 'discharges',
    title: 'Discharges',
    titleMr: 'डिस्चार्ज',
    collection: 'discharges',
    dateFieldForLock: 'dischargeDate',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('dischargeDate', 'Discharge Date', { required: true }),
      en('type', 'Type', ['normal', 'family-request', 'transfer', 'death', 'absconded', 'government-order'], { required: true }),
      str('reason', 'Reason'),
      str('certificateUrl', 'Discharge Certificate URL'),
      str('destinationInstitution', 'Destination Institution'),
      txt('notes', 'Notes'),
    ],
  },
  {
    code: 'transfers',
    title: 'Transfers',
    titleMr: 'स्थानांतरण',
    collection: 'transfers',
    fields: [
      ref('residentId', 'Resident', 'residents', { required: true, index: true }),
      dt('transferDate', 'Transfer Date', { required: true }),
      en('transferType', 'Type', ['room', 'building', 'institution'], { required: true }),
      str('fromLocation', 'From'),
      str('toLocation', 'To'),
      str('reason', 'Reason'),
    ],
  },
  {
    code: 'admissions',
    title: 'Admissions',
    titleMr: 'प्रवेश',
    collection: 'admissions',
    searchableFields: ['applicantName', 'applicationNumber'],
    fields: [
      str('applicationNumber', 'Application Number', { unique: true, index: true }),
      str('applicantName', 'Applicant Name', { required: true }),
      dt('applicationDate', 'Application Date', { required: true }),
      num('age', 'Age'),
      en('gender', 'Gender', ['male', 'female', 'other']),
      str('phone', 'Phone'),
      str('aadhaar', 'Aadhaar'),
      txt('address', 'Address'),
      txt('medicalSummary', 'Medical Summary'),
      str('documentsUrls', 'Document URLs'),
      en('priority', 'Priority', ['normal', 'urgent', 'emergency'], { default: 'normal', index: true }),
      en('status', 'Status', ['applied', 'documents-verified', 'medical-cleared', 'approved', 'room-allocated', 'admitted', 'rejected', 'cancelled', 'waiting'], { default: 'applied', index: true }),
      str('rejectionReason', 'Rejection Reason'),
      ref('roomId', 'Room', 'rooms'),
      ref('bedId', 'Bed', 'beds'),
      ref('residentId', 'Resident', 'residents'),
      dt('admittedDate', 'Admitted Date'),
    ],
    workflow: {
      field: 'status',
      states: ['applied', 'documents-verified', 'medical-cleared', 'approved', 'room-allocated', 'admitted', 'rejected', 'cancelled', 'waiting'] as const,
      initial: 'applied',
      transitions: {
        applied: ['documents-verified', 'waiting', 'rejected', 'cancelled'],
        waiting: ['documents-verified', 'cancelled'],
        'documents-verified': ['medical-cleared', 'rejected'],
        'medical-cleared': ['approved', 'rejected'],
        approved: ['room-allocated'],
        'room-allocated': ['admitted'],
        admitted: [],
        rejected: [],
        cancelled: [],
      },
      transitionRoles: ['assistant-manager', 'institution-head'],
    },
    onTransitionHook: 'admission-approve',
  },
];
