apiVersion: v1
kind: Secret
metadata:
  name: igohms-secrets
  namespace: igohms
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://user:password@cluster.mongodb.net/igohms?retryWrites=true
  SESSION_SIGNING_KEY: change-me-to-a-256-bit-secret
  FIREBASE_PROJECT_ID: change-me
  FIREBASE_PRIVATE_KEY: change-me
  FIREBASE_CLIENT_EMAIL: change-me
